export const PHASES=Object.freeze(['arrival','chest','letter','invitation','writing','review','receipt']);
const transitions={arrival:['chest','writing'],chest:['arrival','letter','invitation'],letter:['invitation','chest'],invitation:['writing','chest'],writing:['review','chest'],review:['writing','receipt','chest'],receipt:['arrival']};
export function canTransition(a,b){return a===b||transitions[a]?.includes(b)===true;}
export function createMachine(initial='arrival'){let current=initial;const listeners=new Set();return{get phase(){return current;},go(next){if(!canTransition(current,next))throw new Error(`Invalid transition ${current} -> ${next}`);const prev=current;current=next;listeners.forEach(fn=>fn(next,prev));},subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn);}};}
export const DRAFT_KEY='magaambya:raincourt:draft:v2';
export function blankDraft(){return{format:'raincourt-draft',schema:2,version:null,name:'',riddles:{},answers:{},page:0,updatedAt:null};}
export function sanitizeDraft(raw,content){if(!raw||typeof raw!=='object'||Array.isArray(raw)||raw.schema!==2||raw.format!=='raincourt-draft')throw new Error('这不是雨庭书院的草稿文件。');const d=blankDraft();d.name=typeof raw.name==='string'?raw.name.slice(0,80):'';d.version=typeof raw.version==='string'?raw.version:null;d.updatedAt=typeof raw.updatedAt==='string'?raw.updatedAt:null;d.page=Number.isInteger(raw.page)?Math.max(0,Math.min(20,raw.page)):0;const safe=(obj,max)=>Object.fromEntries(Object.entries(obj&&typeof obj==='object'&&!Array.isArray(obj)?obj:{}).filter(([k,v])=>/^[a-zA-Z0-9_-]{1,80}$/.test(k)&&!['__proto__','constructor','prototype'].includes(k)&&typeof v==='string').map(([k,v])=>[k,v.slice(0,max)]));d.riddles=safe(raw.riddles,40);d.answers=safe(raw.answers,10000);if(content){d.riddles=Object.fromEntries(content.page1_riddles.filter(q=>q.options.some(o=>o.key===d.riddles[q.id])).map(q=>[q.id,d.riddles[q.id]]));d.answers=Object.fromEntries(content.page2_exam.flatMap(g=>g.questions).filter(q=>q.id in d.answers).map(q=>[q.id,d.answers[q.id]]));d.page=Math.min(d.page,content.page2_exam.length+1);}return d;}
export function loadDraft(storage){try{const text=(storage??globalThis.localStorage).getItem(DRAFT_KEY);return text?sanitizeDraft(JSON.parse(text)):blankDraft();}catch{return blankDraft();}}
export function persistDraft(d,storage){d.updatedAt=new Date().toISOString();(storage??globalThis.localStorage).setItem(DRAFT_KEY,JSON.stringify(d));}
export function missingAnswers(d,c){const out=[];if(!d.name.trim())out.push({page:0,id:'player-name',message:'请写下你的署名。'});for(const q of c.page1_riddles)if(!d.riddles[q.id])out.push({page:1,id:q.id,message:'还有尚未作答的学前问答。'});c.page2_exam.forEach((g,i)=>g.questions.forEach(q=>{if(q.required!==false&&!d.answers[q.id]?.trim())out.push({page:i+2,id:q.id,message:'请完成本页必答题。'});}));return out;}
export function completion(d,c){if(!c)return{done:0,total:1};const required=c.page2_exam.flatMap(g=>g.questions).filter(q=>q.required!==false);return{total:1+c.page1_riddles.length+required.length,done:Number(Boolean(d.name.trim()))+c.page1_riddles.filter(q=>d.riddles[q.id]).length+required.filter(q=>d.answers[q.id]?.trim()).length};}
export const ease=t=>t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;
export function seeded(seed=42){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
