from browser_harness import *
from datetime import datetime,timezone
REPORT={'environment':('Chromium live HTTP navigation and real Storage' if os.environ.get('LIVE_BROWSER')=='1' else 'Chromium about:blank fixture; real local HTTP API; in-memory Storage fixture; static courtyard (Three dependency unavailable)'),'checks':[],'errors':[]}
def check(name,condition):
 print(name, bool(condition), flush=True)
 REPORT['checks'].append({'name':name,'passed':bool(condition)})
 if not condition:raise AssertionError(name)
CONTENT=json.loads((ROOT/'server/data/exam-content.json').read_text(encoding='utf-8'))
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_EXECUTABLE') or ('/usr/bin/chromium' if Path('/usr/bin/chromium').exists() else None),headless=True,args=['--no-sandbox'])
 page=open_fixture(browser)
 page.on('pageerror',lambda e:REPORT['errors'].append(str(e)))
 check('Home renders',page.locator('h1').count()==1)
 check('No horizontal overflow on desktop',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
 page.locator('[data-action=branches]').click();check('Five branches dialog',page.locator('.branches article').count()==5);page.keyboard.press('Escape');check('Dialog Escape',not page.locator('#dialog').evaluate('e=>e.open'))
 page.locator('[data-action=approach]').click();page.locator('#spell').fill('wrong-code');page.locator('#unlock-form button').click();page.wait_for_timeout(300);check('Wrong unlock rejected',len(page.locator('#unlock-error').inner_text())>0)
 page.locator('#spell').fill('jatembe');page.locator('#unlock-form button').click();page.wait_for_selector('[data-action=unseal]');check('Unlock enters sealed letter',page.evaluate('__RAINCOURT__.phase')=='letter')
 page.locator('[data-action=unseal]').click();page.wait_for_selector('.invitation-paper');page.screenshot(path=str(ROOT/'previews/invitation-desktop.png'));check('Seal enters letter',page.evaluate('__RAINCOURT__.phase')=='invitation')
 page.locator('[data-action=write]').click();page.wait_for_selector('#player-name');page.screenshot(path=str(ROOT/'previews/folio-desktop.png'))
 page.locator('[data-action=next]').click();check('Missing signature remains on name page',page.locator('#player-name').count()==1)
 page.locator('#player-name').fill('Raincourt QA <script>');page.locator('[data-action=next]').click();check('Riddle page',page.locator('fieldset.riddle').count()==len(CONTENT['page1_riddles']))
 for q in CONTENT['page1_riddles']:page.locator(f'input[name="{q["id"]}"]').first.check(force=True)
 page.locator('[data-action=next]').click();page.wait_for_timeout(500);check('Incorrect riddle rejected',page.locator('.riddle.invalid').count()>0)
 for q in CONTENT['page1_riddles']:page.locator(f'input[name="{q["id"]}"][value="{q["correct_key"]}"]').check(force=True)
 page.locator('[data-action=next]').click();page.wait_for_selector('[data-answer]');check('Riddles accepted by server',page.locator('[data-answer]').count()>0)
 for i,g in enumerate(CONTENT['page2_exam']):
  if i==0:
   page.screenshot(path=str(ROOT/'previews/questions-desktop.png'),full_page=True)
   page.locator('[data-action=next]').click();check('Required essay blocked',page.locator('.essay.invalid').count()>0)
  for q in g['questions']:page.locator(f'[data-answer="{q["id"]}"]').fill('A considered answer about learning and community.\nNo embedded markup should execute: <img src=x onerror=alert(1)>.')
  page.locator('[data-action=next]').click();page.wait_for_timeout(250)
 page.wait_for_selector('.review-paper');check('Review before submission',page.evaluate('__RAINCOURT__.phase')=='review')
 check('Untrusted name escaped',page.locator('.review-name').inner_text().find('<script>')>=0)
 check('Untrusted answer escaped',page.locator('.review-answer img').count()==0)
 page.screenshot(path=str(ROOT/'previews/review-desktop.png'),full_page=True)
 page.locator('[data-action=submit]').click();check('Consent required',len(page.locator('#submit-error').inner_text())>0)
 page.locator('#consent').check();page.locator('[data-action=submit]').click();page.wait_for_selector('.receipt-paper');check('Real server receipt',page.locator('.receipt-meta').inner_text().find('sub_')>=0)
 page.screenshot(path=str(ROOT/'previews/receipt-desktop.png'))
 with page.expect_download() as d:page.locator('[data-action=receipt-export]').click()
 check('Receipt download',d.value.suggested_filename.endswith('.json'))
 mobile=open_fixture(browser,390,844);mobile.on('pageerror',lambda e:REPORT['errors'].append(str(e)))
 check('Mobile home no overflow',mobile.evaluate('document.documentElement.scrollWidth<=innerWidth'))
 mobile.locator('[data-action=direct]').click();mobile.locator('#spell').fill('jatembe');mobile.locator('#unlock-form button').click();mobile.wait_for_selector('[data-action=write]');mobile.locator('[data-action=write]').click();mobile.wait_for_selector('#player-name')
 mobile.screenshot(path=str(ROOT/'previews/folio-mobile.png'),full_page=True)
 check('Mobile folio no overflow',mobile.evaluate('document.documentElement.scrollWidth<=innerWidth'))
 mobile.locator('[data-page="2"]').click();mobile.screenshot(path=str(ROOT/'previews/questions-mobile.png'),full_page=True)
 check('Mobile material and answer visible',mobile.locator('blockquote').is_visible() and mobile.locator('textarea').first.is_visible())
 check('Mobile questions no overflow',mobile.evaluate('document.documentElement.scrollWidth<=innerWidth'))
 mobile.locator('[data-action=settings]').click();mobile.locator('#settings-save').click();check('Settings dialog closes',not mobile.locator('#dialog').evaluate('e=>e.open'))
 admin=open_fixture(browser,1440,1000,admin=True);admin.on('pageerror',lambda e:REPORT['errors'].append(str(e)))
 admin.locator('#admin-key').fill('bad');admin.locator('#admin-login-form button').click();admin.wait_for_timeout(300);check('Admin wrong password rejected',len(admin.locator('#login-error').inner_text())>0)
 admin.locator('#admin-key').fill('change-me');admin.locator('#admin-login-form button').click();admin.wait_for_selector('.letters-ledger');check('Admin sees actual records',admin.locator('[data-open]').count()>0)
 admin.screenshot(path=str(ROOT/'previews/admin-desktop.png'))
 admin.locator('[data-open]').first.click();admin.wait_for_selector('#review-note');admin.locator('#review-note').fill('Browser review test');admin.locator('#review-status').select_option('reviewed');admin.locator('#review-form button[type=submit]').click();admin.wait_for_timeout(300);check('Review saved',admin.locator('.status-dot.reviewed').count()>0)
 admin.locator('[data-tab=content]').click();check('Question editor mounted',admin.locator('[data-bind]').count()>10)
 admin.locator('[data-tab=settings]').click();check('Settings data fetched',admin.locator('input[name=unlock_spell]').input_value()=='jatembe')
 check('No uncaught browser errors',len(REPORT['errors'])==0)
 browser.close()
REPORT['time']=datetime.now(timezone.utc).isoformat()
(ROOT/'docs/browser-results.json').write_text(json.dumps(REPORT,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps(REPORT,ensure_ascii=True,indent=2))
