import test from 'node:test';import assert from 'node:assert/strict';import {once} from 'node:events';import {readFile,writeFile} from 'node:fs/promises';
import {createServer} from '../server/app.js';import {createLimiter} from '../server/utils/limiter.js';import {EXAM_CONTENT_PATH,SUBMISSIONS_PATH} from '../server/constants.js';
async function fixture(t){const server=createServer();server.listen(0,'127.0.0.1');await once(server,'listening');t.after(()=>server.close());const base=`http://127.0.0.1:${server.address().port}`;const call=async(path,body,token,method=body?'POST':'GET')=>fetch(base+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{})},...(body?{body:JSON.stringify(body)}:{})});return{server,base,call};}
async function attempt(call){const r=await call('/api/public/unlock',{spell:'jatembe'});return(await r.json()).data.attempt_token;}
test('Private JSON files are not statically exposed',async t=>{const{call}=await fixture(t);for(const p of ['/server/data/settings.json','/server/data/submissions.json','/server/data/exam-content.json','/.env'])assert.equal((await call(p)).status,404);});
test('HTML has a restrictive security policy',async t=>{const{call}=await fixture(t);const r=await call('/');assert.equal(r.status,200);assert.match(r.headers.get('content-security-policy'),/script-src 'self'/);assert.equal(r.headers.get('x-content-type-options'),'nosniff');});
test('All admin reads require admin authentication',async t=>{const{call}=await fixture(t);for(const p of ['settings','stats','submissions','exam-content'])assert.equal((await call('/api/admin/'+p)).status,401);});
test('Public token cannot access administrator data',async t=>{const{call}=await fixture(t),token=await attempt(call);assert.equal((await call('/api/admin/settings',null,token)).status,401);});
test('Malformed JSON is a client error',async t=>{const{base}=await fixture(t);const r=await fetch(base+'/api/public/unlock',{method:'POST',body:'{broken',headers:{'Content-Type':'application/json'}});assert.equal(r.status,400);});
test('Array JSON is rejected',async t=>{const{call}=await fixture(t);assert.equal((await call('/api/public/unlock',[])).status,400);});
test('Submitting without complete essays is rejected',async t=>{const{call}=await fixture(t),token=await attempt(call),c=JSON.parse(await readFile(EXAM_CONTENT_PATH,'utf8'));const r=await call('/api/public/submissions',{player_name:'Applicant',riddle_answers:Object.fromEntries(c.page1_riddles.map(q=>[q.id,q.correct_key])),exam_answers:{}},token);assert.equal(r.status,422);});
test('Wrong riddle answer cannot be bypassed on submission',async t=>{const{call}=await fixture(t),token=await attempt(call);const r=await call('/api/public/submissions',{player_name:'Applicant',riddle_answers:{q1:'Z'},exam_answers:{e1:'a',e2:'b',e3:'c'}},token);assert.equal(r.status,422);});
test('Retrying an attempt returns the same persisted receipt',async t=>{const original=await readFile(SUBMISSIONS_PATH);t.after(()=>writeFile(SUBMISSIONS_PATH,original));const{call}=await fixture(t),token=await attempt(call),c=JSON.parse(await readFile(EXAM_CONTENT_PATH,'utf8')),body={player_name:'Retry',riddle_answers:Object.fromEntries(c.page1_riddles.map(q=>[q.id,q.correct_key])),exam_answers:Object.fromEntries(c.page2_exam.flatMap(g=>g.questions).map(q=>[q.id,'Considered answer']))};const a=await(await call('/api/public/submissions',body,token)).json(),b=await(await call('/api/public/submissions',body,token)).json();assert.equal(a.data.submission_id,b.data.submission_id);});
test('Changed question version invalidates an old attempt',async t=>{const original=await readFile(EXAM_CONTENT_PATH);t.after(()=>writeFile(EXAM_CONTENT_PATH,original));const{call}=await fixture(t),token=await attempt(call),c=JSON.parse(original);c.updated_at='2999-01-01T00:00:00.000Z';await writeFile(EXAM_CONTENT_PATH,JSON.stringify(c));assert.equal((await call('/api/public/exam',null,token)).status,409);});
test('Admin rate limit is bounded and expires',()=>{let time=0;const limit=createLimiter({now:()=>time}),req={method:'POST',url:'/api/admin/session',socket:{remoteAddress:'test'}},response={setHeader(){},end(){}};for(let i=0;i<12;i++)assert.equal(limit(req,response),false);assert.equal(limit(req,response),true);assert.equal(response.statusCode,429);time=61000;assert.equal(limit(req,response),false);});
test('Non-authentication endpoints are not counted by login limiter',()=>{const limit=createLimiter(),req={method:'GET',url:'/api/public/exam',socket:{remoteAddress:'test'}};for(let i=0;i<100;i++)assert.equal(limit(req,{}),false);});
