import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PHASES,createMachine,canTransition,blankDraft,sanitizeDraft,loadDraft,persistDraft,missingAnswers,completion,ease,seeded,DRAFT_KEY} from '../web/lib/state.js';
import {esc} from '../web/lib/dom.js';
const content=JSON.parse(await readFile(new URL('../server/data/exam-content.json',import.meta.url),'utf8'));
const store=()=>{const map=new Map();return{getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)};};
test('Flow follows all seven phases',()=>{const m=createMachine();for(const phase of PHASES.slice(1))m.go(phase);assert.equal(m.phase,'receipt');});
test('Cannot jump from arrival to receipt',()=>assert.throws(()=>createMachine().go('receipt')));
test('Review can return to writing',()=>assert.equal(canTransition('review','writing'),true));
test('Machine notifies and unsubscribes',()=>{const m=createMachine();let count=0;const off=m.subscribe(()=>count++);m.go('chest');off();m.go('letter');assert.equal(count,1);});
test('Unknown transitions are rejected',()=>assert.equal(canTransition('unknown','receipt'),false));
test('Blank drafts use independent answer objects',()=>{const a=blankDraft(),b=blankDraft();a.answers.a='x';assert.deepEqual(b.answers,{});});
test('Reject foreign draft format',()=>assert.throws(()=>sanitizeDraft({schema:2,format:'other'})));
test('Reject arrays as drafts',()=>assert.throws(()=>sanitizeDraft([])));
test('Limit signature and essay lengths',()=>{const d=sanitizeDraft({...blankDraft(),name:'x'.repeat(100),answers:{a:'a'.repeat(12000)}});assert.equal(d.name.length,80);assert.equal(d.answers.a.length,10000);});
test('Drop unsafe object keys',()=>{const d=blankDraft();d.answers=JSON.parse('{"__proto__":"x","constructor":"x","safe":"x"}');assert.deepEqual(sanitizeDraft(d).answers,{safe:'x'});});
test('Filter obsolete questions on schema update',()=>{const d=blankDraft();d.answers.deleted='old';d.answers.e1='new';assert.deepEqual(sanitizeDraft(d,content).answers,{e1:'new'});});
test('Drop unknown radio options',()=>{const d=blankDraft();d.riddles.q1='Z';assert.deepEqual(sanitizeDraft(d,content).riddles,{});});
test('Clamp imported page position',()=>assert.equal(sanitizeDraft({...blankDraft(),page:999},content).page,content.page2_exam.length+1));
test('Storage round trip',()=>{const s=store(),d=blankDraft();d.name='Applicant';persistDraft(d,s);assert.equal(loadDraft(s).name,'Applicant');assert.ok(d.updatedAt);});
test('Corrupt stored draft recovers without crashing',()=>{const s=store();s.setItem(DRAFT_KEY,'broken');assert.deepEqual(loadDraft(s),blankDraft());});
test('Unavailable storage recovers on read',()=>assert.deepEqual(loadDraft({getItem(){throw new Error('blocked');}}),blankDraft()));
test('Unavailable storage propagates save failure',()=>assert.throws(()=>persistDraft(blankDraft(),{setItem(){throw new Error('quota');}})));
test('Missing answers map to exact pages',()=>{const missing=missingAnswers(blankDraft(),content);assert.equal(missing[0].page,0);assert.equal(missing.find(x=>x.id==='q1').page,1);assert.equal(missing.find(x=>x.id==='e1').page,2);assert.equal(missing.find(x=>x.id==='e3').page,3);});
test('Complete draft has no missing fields',()=>{const d=blankDraft();d.name='Applicant';for(const q of content.page1_riddles)d.riddles[q.id]=q.correct_key;for(const q of content.page2_exam.flatMap(g=>g.questions))d.answers[q.id]='Answer';assert.equal(missingAnswers(d,content).length,0);const p=completion(d,content);assert.equal(p.done,p.total);});
test('Whitespace is not a written answer',()=>{const d=blankDraft();d.name='   ';d.answers.e1='\n';assert.equal(completion(d,content).done,0);});
test('HTML is escaped, not injected',()=>assert.equal(esc('<img a="x">&'),'&lt;img a=&quot;x&quot;&gt;&amp;'));
test('Easing has correct endpoints and midpoint',()=>{assert.equal(ease(0),0);assert.equal(ease(.5),.5);assert.equal(ease(1),1);});
test('Procedural materials use deterministic seeds',()=>{const a=seeded(13),b=seeded(13);for(let i=0;i<100;i++)assert.equal(a(),b());});

test('Expired review credentials can return to the seal without losing the draft',()=>{const m=createMachine('review');m.go('chest');assert.equal(m.phase,'chest');});
