import {$,$$,esc,icon,toast,openDialog,saveFile,focusHeading} from './lib/dom.js';
import {request} from './lib/api.js';
const KEY='raincourt:admin';let token='',tab='letters',records=[],selected=null,settings=null,content=null,busy=false,filter='all',search='';
const statuses={submitted:'待阅',reviewed:'已阅',archived:'已归档'};
const date=v=>new Date(v).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
const api=(path,options={})=>request('/api/admin/'+path,{...options,token});
function head(){return `<header class="admin-head"><a href="/" class="brand"><img src="/assets/crest.svg" width="39" height="39" alt=""><span>玛甘比学院<small>MAGAAMBYA</small></span></a><div><span class="admin-designation">雨庭档案室</span>${token?'<button class="understated" id="logout">退出</button>':''}<a class="understated" href="/">返回庭院 ${icon('arrow',15)}</a></div></header>`;}
export async function mount(){document.body.className='administration scene-flat';const link=document.createElement('link');link.rel='stylesheet';link.href='/admin.css';document.head.append(link);try{token=sessionStorage.getItem(KEY)||'';}catch{}if(!token)return login();renderLoading();await load();}
function login(message=''){token='';$('#app').innerHTML=head()+`<main id="main" class="admin-login"><section><p class="eyebrow">THE RAINCOURT ARCHIVE</p><h1 tabindex="-1">每一封来信，<br>都值得认真读完。</h1><p>主持人阅卷入口</p><form id="admin-login-form"><label for="admin-key" class="field-label">管理口令</label><input type="password" id="admin-key" autocomplete="current-password" required maxlength="200"><p id="login-error" class="form-error" role="alert">${esc(message)}</p><button class="paper-button" type="submit">进入档案室 ${icon('arrow',17)}</button></form></section><img src="/assets/botanical.svg" alt=""></main>`;$('#admin-login-form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const b=$('#admin-login-form button');b.disabled=true;try{const data=await request('/api/admin/session',{method:'POST',body:{passphrase:$('#admin-key').value}});token=data.admin_token;try{sessionStorage.setItem(KEY,token);}catch{}await load();}catch(error){$('#login-error').textContent=error.message;b.disabled=false;}finally{busy=false;}};focusHeading();}
function renderLoading(){$('#app').innerHTML=head()+'<main class="admin-loading">正在整理书笺……</main>';}
async function load(){try{const [items,s,c]=await Promise.all([api('submissions'),api('settings'),api('exam-content')]);records=items.items;settings=s;content=c;render();}catch(error){if(error.status===401){try{sessionStorage.removeItem(KEY);}catch{}login('阅览凭据已过期，请重新进入。');}else{$('#app').innerHTML=head()+`<main class="admin-loading"><p>${esc(error.message)}</p><button class="paper-button" id="reload">重新取信</button></main>`;$('#reload').onclick=load;}}}
function render(){document.body.className='administration scene-flat';$('#app').innerHTML=head()+`<main id="main" class="archive-shell"><aside class="archive-nav"><p>雨庭档案<small>LETTERS & RECORDS</small></p><nav>${[['letters','来信'],['content','题笺'],['settings','收信设置']].map(([key,label],i)=>`<button data-tab="${key}" class="${tab===key?'active':''}"><span>0${i+1}</span>${label}</button>`).join('')}</nav><span class="archive-total">${records.length} 封来信</span></aside><section class="archive-workspace">${tab==='letters'?lettersView():tab==='content'?contentView():settingsView()}</section></main><footer class="admin-footer">MAGAAMBYA <span>·</span> NANTAMBU</footer>`;bind();}
function lettersView(){const items=records.filter(r=>(filter==='all'||r.status===filter)&&r.player_name.toLowerCase().includes(search.toLowerCase()));return `<header class="workspace-heading"><div><p class="eyebrow">INCOMING LETTERS</p><h1 tabindex="-1">来信</h1></div><button class="understated" id="refresh">重新取信 ${icon('arrow',16)}</button></header><div class="archive-summary"><div><strong>${records.length}</strong><span>全部来信</span></div><div><strong>${records.filter(r=>r.status==='submitted').length}</strong><span>等待阅览</span></div><div><strong>${records.filter(r=>r.status==='reviewed').length}</strong><span>已经批阅</span></div></div><div class="archive-toolbar"><label class="sr-only" for="record-search">查找署名</label><input id="record-search" type="search" placeholder="查找来信人" value="${esc(search)}"><label class="sr-only" for="record-filter">阅览状态</label><select id="record-filter">${[['all','全部状态'],...Object.entries(statuses)].map(([k,v])=>`<option value="${k}" ${k===filter?'selected':''}>${v}</option>`).join('')}</select></div><div class="letters-ledger">${items.length?`<table><thead><tr><th>来信人</th><th>收信时间</th><th>状态</th><th><span class="sr-only">阅览</span></th></tr></thead><tbody>${items.map(r=>`<tr><td><button class="record-name" data-open="${esc(r.id)}">${esc(r.player_name)}</button></td><td>${date(r.created_at)}</td><td><span class="status-dot ${esc(r.status)}">${statuses[r.status]||'待阅'}</span></td><td><button class="icon-button" data-open="${esc(r.id)}" aria-label="阅览 ${esc(r.player_name)} 的来信">${icon('arrow',16)}</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty-archive"><img src="/assets/botanical.svg" alt=""><p>这一页，尚在等待来信。</p></div>'}</div>`;}
function settingsView(){return `<header class="workspace-heading"><div><p class="eyebrow">ADMISSIONS OFFICE</p><h1 tabindex="-1">收信设置</h1></div></header><form id="settings-form" class="archive-form"><label>学院页面标题<input name="site_title" value="${esc(settings.site_title)}" maxlength="80" required></label><label>启封词<input name="unlock_spell" value="${esc(settings.unlock_spell)}" maxlength="128" required autocomplete="off"></label><label class="switch-label"><span>接收新的来信</span><input type="checkbox" name="submission_enabled" ${settings.submission_enabled?'checked':''}></label><p class="archive-help">暂停收信不会删除已有档案。求学者仍可阅读题笺，并在本机保存草稿。</p><p class="form-error" id="settings-error" role="alert"></p><button class="paper-button" type="submit">保存设置 ${icon('check',17)}</button></form>`;}
function contentView(){return `<header class="workspace-heading"><div><p class="eyebrow">THE ADMISSIONS FOLIO</p><h1 tabindex="-1">题笺</h1></div><button class="understated" id="export-content">导出题笺 ${icon('download',16)}</button></header><p class="archive-help">题笺更新后，正在填写的来信需要重新启封并核对。本机草稿不会被删除。</p><form id="content-form" class="content-editor"><h2>学前问答</h2>${content.page1_riddles.map((q,i)=>`<details class="editor-section" ${i===0?'open':''}><summary>${String(i+1).padStart(2,'0')} ${esc(q.question)}</summary><label>问题<textarea data-bind="page1_riddles.${i}.question" maxlength="5000" required>${esc(q.question)}</textarea></label><div class="editor-options">${q.options.map((o,j)=>`<label><span>${esc(o.key)}</span><input data-bind="page1_riddles.${i}.options.${j}.text" value="${esc(o.text)}" maxlength="2000" required></label>`).join('')}</div><label>正确答案<select data-bind="page1_riddles.${i}.correct_key">${q.options.map(o=>`<option value="${esc(o.key)}" ${o.key===q.correct_key?'selected':''}>${esc(o.key)}</option>`).join('')}</select></label></details>`).join('')}<h2>阅读与书写</h2>${content.page2_exam.map((g,i)=>`<details class="editor-section"><summary>材料 ${String(i+1).padStart(2,'0')} <span>${g.questions.length} 道问答</span></summary><label>材料内容<textarea rows="8" data-bind="page2_exam.${i}.reading_material" maxlength="30000" required>${esc(g.reading_material)}</textarea></label>${g.questions.map((q,j)=>`<div class="editor-question"><label>问题 ${j+1}<textarea data-bind="page2_exam.${i}.questions.${j}.question" maxlength="5000" required>${esc(q.question)}</textarea></label><div class="editor-question-meta"><label>分值<input type="number" min="0" max="1000" data-number data-bind="page2_exam.${i}.questions.${j}.points" value="${q.points}" required></label><label class="switch-label">必答<input type="checkbox" data-bind="page2_exam.${i}.questions.${j}.required" ${q.required!==false?'checked':''}></label></div></div>`).join('')}</details>`).join('')}<div class="editor-save"><p class="form-error" id="content-error" role="alert"></p><button class="paper-button" type="submit">发布题笺 ${icon('check',17)}</button><label class="understated import-label">导入题笺文件<input type="file" id="import-content" accept="application/json,.json"></label></div></form>`;}
function bind(){
 $('#logout').onclick=()=>{try{sessionStorage.removeItem(KEY);}catch{}token='';login();};
 $$('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();focusHeading();});
 $('#refresh')?.addEventListener('click',load);$('#record-filter')?.addEventListener('change',e=>{filter=e.target.value;render();});
 $('#record-search')?.addEventListener('input',e=>{search=e.target.value;const position=e.target.selectionStart;render();const el=$('#record-search');el.focus();try{el.setSelectionRange(position,position);}catch{}});
 $$('[data-open]').forEach(b=>b.onclick=()=>openRecord(b.dataset.open));
 $('#settings-form')?.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;const b=e.target.querySelector('button[type=submit]');b.disabled=true;$('#settings-error').textContent='';const f=new FormData(e.target);try{settings=await api('settings',{method:'PUT',body:{site_title:f.get('site_title'),unlock_spell:f.get('unlock_spell'),submission_enabled:f.get('submission_enabled')==='on'}});toast('收信设置已保存。');}catch(error){$('#settings-error').textContent=error.message;}finally{busy=false;b.disabled=false;}});
 $('#export-content')?.addEventListener('click',()=>saveFile('玛甘比-入学题笺.json',content));
 $('#content-form')?.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;const next=structuredClone(content);$$('[data-bind]').forEach(el=>{const keys=el.dataset.bind.split('.');let parent=next;for(const k of keys.slice(0,-1))parent=parent[k];parent[keys.at(-1)]=el.type==='checkbox'?el.checked:el.hasAttribute('data-number')?Number(el.value):el.value;});await publish(next);});
 $('#import-content')?.addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>1500000)return toast('题笺文件不能超过 1.5 MB。');try{const next=JSON.parse(await file.text());if(!Array.isArray(next.page1_riddles)||!Array.isArray(next.page2_exam))throw new Error('题笺格式不正确。');openDialog(`<p class="eyebrow">REPLACE THE FOLIO</p><h2>用这份题笺替换现有内容？</h2><p class="dialog-intro">${next.page1_riddles.length} 道学前问答，${next.page2_exam.length} 份阅读材料。替换后，正在填写的求学者需要重新启封。</p><div class="dialog-actions"><button id="confirm-import" class="paper-button">确认替换 ${icon('check',16)}</button></div>`,()=>{$('#confirm-import').onclick=async()=>{$('#dialog').close();await publish(next);};});}catch(error){toast(error.message);}});
}
async function publish(next){busy=true;const b=$('#content-form button[type=submit]');if(b)b.disabled=true;try{await api('exam-content',{method:'PUT',body:next});content=await api('exam-content');render();toast('新题笺已发布。');}catch(error){if($('#content-error'))$('#content-error').textContent=error.message;else toast(error.message);}finally{busy=false;if(b?.isConnected)b.disabled=false;}}
async function openRecord(id){try{selected=await api('submissions/'+encodeURIComponent(id));const r=selected;openDialog(`<p class="eyebrow">A LETTER TO THE MAGAAMBYA</p><div class="record-heading"><h2>${esc(r.player_name)}</h2><span>${date(r.created_at)}</span></div><div class="record-answers">${(r.content_snapshot||[]).map(g=>g.questions.map(q=>`<section><h3>${esc(q.question)}</h3><p>${esc(r.exam_answers[q.id]||'未作答')}</p></section>`).join('')).join('')}</div><form id="review-form"><label class="field-label" for="review-status">阅览状态</label><select id="review-status">${Object.entries(statuses).map(([k,v])=>`<option value="${k}" ${r.status===k?'selected':''}>${v}</option>`).join('')}</select><label class="field-label" for="review-note">批注</label><textarea id="review-note" maxlength="10000" rows="4">${esc(r.review_note||'')}</textarea><p class="form-error" id="review-error" role="alert"></p><div class="dialog-actions"><button class="paper-button" type="submit">保存批阅 ${icon('check',17)}</button><button class="understated" type="button" id="record-export">导出来信</button></div></form>`,()=>{$('#record-export').onclick=()=>saveFile('玛甘比-来信-'+r.id+'.json',selected);$('#review-form').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button[type=submit]');b.disabled=true;try{const patch=await api('submissions/'+encodeURIComponent(id),{method:'PATCH',body:{status:$('#review-status').value,review_note:$('#review-note').value}});selected={...selected,...patch};const item=records.find(r=>r.id===id);if(item)item.status=patch.status;$('#dialog').close();render();toast('批阅已保存。');}catch(error){$('#review-error').textContent=error.message;b.disabled=false;}};});}catch(error){if(error.status===401){token='';login('阅览凭据已过期。');}else toast(error.message);}}
